# Generated by Django 4.1.6 on 2023-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilantix', '0003_policstation_securitycamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='policstation',
            name='name',
            field=models.CharField(default='na', max_length=30),
        ),
    ]
